use_frameworks!

target 'JBPersistenceStore-Protocols_Example' do
  pod 'JBPersistenceStore-Protocols', :path => '../'
end

target 'JBPersistenceStore-Protocols_Tests' do
  pod 'JBPersistenceStore-Protocols', :path => '../'

  
end
